### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Xuanwo** [hack1day/wechat-screenshot-generator#3]
An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by xcatliu** [comment]
这个项目烂尾啦哈哈 😭
@hxlniada @xnn5566

**Comment by xcatliu** [comment]
@hxlniada @xnn5566 来一起搞完吧～

**Comment by asjdf** [comment]
进度如何?

**Comment by xcatliu** [comment]
@asjdf 烂尾了。。这个工具网上一搜一大把
